gomod:
  proxy: true
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
brews:
- tap:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/caarlos0/svu
  description: Semantic Version Util.
nfpms:
- homepage:  https://github.com/caarlos0/svu
  description: Semantic Version Util.
  maintainer: Carlos Alexandro Becker <pkg@carlosbecker.com>
  license: MIT
  vendor: Becker Software
  formats:
  - apk
  - deb
  - rpm
