build:
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
brews:
- tap:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/caarlos0/svu
  description: Semantic Version Util.
nfpms:
- homepage:  https://github.com/caarlos0/svu
  description: Semantic Version Util.
  maintainer: Carlos Alexandro Becker <pkg@carlosbecker.com>
  license: MIT
  vendor: Becker Software
  formats:
  - apk
  - deb
  - rpm
